<a href="https://colab.research.google.com/github/Joc02/7771531-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P2/P2C3%20-%20Filtrez%20les%20donn%C3%A9es%20du%20data%20frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)

# Filtrez les données du dataframe

Nous allons à présent aller un peu plus loin dans la manipulation de nos prêts bancaires. Les demandes suivantes ont été formulées par le responsable du service prêt de notre établissement :
- Le taux d’endettement autorisé est de 35%. Pourriez vous me communiquer le nombre de personnes ayant dépassé ce seuil ?
- Même question, mais cette fois ci uniquement sur l’agence Parisienne
- Pour faciliter le traitement d’éventuelles futures demandes de prêts, pourriez vous ajouter une variable nommée `risque` qui nous permettrait d’identifier les clients risqués facilement
- Combien de prêts automobiles ont été accordés ? Quel est le coût total moyen de ces derniers ?
- Quel est le bénéfice mensuel total réalisé par l’agence Toulousaine ?

Vous allez devoir mettre en application l’ensemble des processus de sélection présentés ci-dessus pour répondre à ces différentes demandes.

In [2]:
import numpy as np
import pandas as pd

In [3]:
# traitement réalisés précédemment
prets = pd.read_csv('https://raw.githubusercontent.com/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/main/data/prets.csv')

# calcul du taux d'endettement
prets['taux_endettement'] = round(prets['remboursement'] * 100 / prets['revenu'], 2)

# renommer taux en taux_interet
prets.rename(columns={'taux':'taux_interet'}, inplace=True)

# calculer le cout total du pret
prets['cout_total'] = prets['remboursement'] * prets['duree']

# calculer les bénéfices mensuels réalisés
prets['benefices'] = round((prets['cout_total'] * prets['taux_interet']/100)/(24), 2)

prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endettement,cout_total,benefices
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.80,271212.0,131.99
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.52,15360.0,23.69
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.50,374355.0,182.97
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.50,132609.6,53.71
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.80,105485.4,44.57

Le taux d’endettement autorisé est de 35%. Pourriez vous me communiquer le nombre de personnes ayant dépassé ce seuil ? vous pourrez me stocker la liste dans une variable à part nommé `clients_risque`

In [39]:
clients_risque = prets.loc[prets['taux_endettement']> 35, :].shape[0]
print(clients_risque)

58

Même question, mais cette fois ci uniquement sur l’agence Parisienne

In [9]:
clients_risque = prets.loc[(prets['taux_endettement']> 35) & (prets['ville']=='PARIS'), :]
clients_risque.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endettement,cout_total,benefices
70,67,PARIS,75014,5598.0,2395.94,240,immobilier,1.136,42.8,575025.6,272.18
75,72,PARIS,75012,5981.0,2230.91,240,immobilier,1.150,37.3,535418.4,256.55
89,85,PARIS,75005,6341.0,2980.27,240,immobilier,1.074,47.0,715264.8,320.08
129,122,PARIS,75001,6536.0,2457.54,120,immobilier,1.038,37.6,294904.8,127.55
143,134,PARIS,75003,2870.0,1021.72,180,immobilier,1.104,35.6,183909.6,84.60

Pour faciliter le traitement d’éventuelles futures demandes de prêts, pourriez vous ajouter une variable nommée `risque` qui aurait pour valeur `Oui` si le client est risqué (taux d’endettement > 35%), `Non` sinon.
Pour se faire, je vous conseille de créer la variable `risque` en l'initialisant à `Non` (ou `Oui`, à votre préférence) et de ne modifier que les lignes concernées par la valeur inverse :

In [11]:
prets['risque'] = 'non'
prets.loc[prets['taux_endettement']> 35, 'risque'] = 'oui'
prets.head(10)

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endettement,cout_total,benefices,risque
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.80,271212.0,131.99,non
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.52,15360.0,23.69,non
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.50,374355.0,182.97,non
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.50,132609.6,53.71,non
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.80,105485.4,44.57,non
5,4,MARSEILLE,13012,1476.0,423.61,240,immobilier,1.209,28.70,101666.4,51.21,non
6,5,PARIS,75016,2476.0,836.89,240,immobilier,1.116,33.80,200853.6,93.40,non
7,6,LYON,69008,1867.0,711.33,240,immobilier,1.196,38.10,170719.2,85.08,oui
8,7,NICE,6000,5486.0,2956.95,300,immobilier,1.184,53.90,887085.0,437.63,oui
9,8,BORDEAUX,33200,3578.0,751.38,180,immobilier,1.316,21.00,135248.4,74.16,non

Combien de prêts automobiles ont été accordés ? Quel est le coût total moyen de ces derniers ?

In [32]:
sum(prets.loc[prets['type'] == 'automobile', 'cout_total']) / len(prets.loc[prets['type'] == 'automobile', :])

13665.0

Quel est le bénéfice mensuel total réalisé par l’agence Toulousaine ?

In [36]:
sum(prets.loc[prets['ville'] == 'TOULOUSE', 'benefices'])

2138.07

Félicitation ! Je vous invite fortement à vérifier vos réponses avec [la correction ci contre](https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P2/P2C3%20-%20Filtrez%20les%20donn%C3%A9es%20du%20data%20frame%20-%20correction.ipynb).